id: '1763168904540'
alias: 'Media: Fix Google TV Apple TV'
description: Switches Android TV to Apple TV HDMI input every 5 seconds when Google
  TV is stuck on Settings or Google TV Launcher
triggers:
- trigger: time_pattern
  seconds: /5
conditions:
- condition: or
  conditions:
  - condition: state
    entity_id: media_player.android_tv_10_0_1_195
    state: Settings
    attribute: app_name
  - condition: state
    entity_id: media_player.android_tv_10_0_1_195
    state: Google TV Launcher
    attribute: app_name
actions:
- action: script.google_tv_apple_tv_input_select
  data: {}
mode: single
enabled: true
