id: '1763575398211'
alias: 'Lighting: Entrance Presence'
description: Turns on lights when someone enters the apartment
triggers:
- trigger: state
  entity_id:
  - binary_sensor.motion_sensor_occupancy_2
  to:
  - 'on'
conditions:
- condition: state
  entity_id: light.shoerack_light
  state:
  - 'off'
- condition: state
  entity_id: input_boolean.iphone_sleep_focus_mode
  state:
  - 'off'
actions:
- action: script.apply_adaptive_lighting
  data:
    target_lights:
      entity_id: light.lights
    transition: 3
mode: single
enabled: true
