id: '1764825433805'
alias: 'System: Nintendo Toy Shutdown'
description: Turns off Nintendo toy when Home Assistant shuts down
triggers:
- trigger: homeassistant
  event: shutdown
conditions: []
actions:
- action: select.select_option
  metadata: {}
  target:
    entity_id: select.nintendo_toy_mode_selector
  data:
    option: 'Off'
mode: single
enabled: true
