id: eating_mode_on
alias: 'Eating: Restore Back Lights'
description: When eating mode is turned on during theater mode, restore back lights
  to adaptive lighting
triggers:
- trigger: state
  entity_id: input_boolean.eating_mode
  from: 'off'
  to: 'on'
conditions:
- condition: state
  entity_id: media_player.matthews_bedroom_2
  state: playing
- condition: template
  value_template: '{{ state_attr(''media_player.matthews_bedroom_2'', ''app_name'')
    != ''Music'' }}'
actions:
- action: script.apply_adaptive_lighting
  data:
    target_lights:
      entity_id:
      - light.living_room_vertical_light_strip
      - light.living_room_pegboard_light_strip
      - light.desk_light_strips
      - light.desk_lamp
    transition: 5
mode: single
enabled: true
